version: "3.8"

services:
  # base url: http://nginx_recipes:80
  # make sure when adding api key scope is "read write"
  db_recipes:
    container_name: db_recipes
    restart: always
    image: postgres:16-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./tandoor.env
    networks:
      default:

  web_recipes:
    container_name: web_recipes
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./tandoor.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      default:

  nginx_recipes:
    container_name: nginx_recipes
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./tandoor.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:rw
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    # Update nginx config for local development
    command: >
      sh -c "
        sed -i 's/server_name .*/server_name _;/' /etc/nginx/conf.d/Recipes.conf &&
        sed -i 's/proxy_set_header .*/proxy_set_header Host localhost;/' /etc/nginx/conf.d/Recipes.conf &&
        nginx -g 'daemon off;'
      "
    networks:
      skylite-ux_devcontainer_default:
      default:

volumes:
  postgresql_data:
  nginx_config:
  staticfiles:

networks:
  default:
  skylite-ux_devcontainer_default:
    external: true
